CREATE PROC FI_SP_AltBeneficiario
    @NOME          VARCHAR (50) ,
	@CPF			  VARCHAR(14),
	@IDCLIENTE		VARCHAR(2)
AS
BEGIN
	UPDATE BENEFICIARIOS
	SET 
		NOME = @NOME, 
		CPF = @CPF
	WHERE IDCLIENTE = @IDCLIENTE
END